/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DanaDesaLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "KADES_ROLE"
      | "KAUR_KEUANGAN_ROLE"
      | "KAUR_ROLE"
      | "SEKDES_ROLE"
      | "authorizeByKades"
      | "disbursements"
      | "executeDisbursement"
      | "getRoleAdmin"
      | "getSisaPagu"
      | "grantRole"
      | "hasRole"
      | "lpjDesaHashes"
      | "proposals"
      | "registerProposal"
      | "rejectIntervention"
      | "renounceRole"
      | "returnForRevision"
      | "revokeRole"
      | "submitDisbursement"
      | "submitLpjDesa"
      | "submitLpjKeuangan"
      | "submitLpjTeknis"
      | "supportsInterface"
      | "totalDisbursedPerProposal"
      | "verifyBySekdes"
      | "verifyHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedByKades"
      | "Disbursed"
      | "DisbursementSubmitted"
      | "InterventionRejected"
      | "LpjDesaSubmitted"
      | "LpjKeuanganSubmitted"
      | "LpjTeknisSubmitted"
      | "ProposalRegistered"
      | "ReturnedForRevision"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "VerifiedBySekdes"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KADES_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KAUR_KEUANGAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "KAUR_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SEKDES_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeByKades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disbursements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDisbursement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSisaPagu",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpjDesaHashes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProposal",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectIntervention",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "returnForRevision",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDisbursement",
    values: [BigNumberish, BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitLpjDesa",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitLpjKeuangan",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitLpjTeknis",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDisbursedPerProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBySekdes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KADES_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "KAUR_KEUANGAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KAUR_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SEKDES_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeByKades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disbursements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDisbursement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSisaPagu",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lpjDesaHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectIntervention",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnForRevision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitDisbursement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitLpjDesa",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitLpjKeuangan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitLpjTeknis",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDisbursedPerProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyBySekdes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace AuthorizedByKadesEvent {
  export type InputTuple = [
    disbursementId: BigNumberish,
    kades: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    disbursementId: bigint,
    kades: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    disbursementId: bigint;
    kades: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisbursedEvent {
  export type InputTuple = [
    disbursementId: BigNumberish,
    kaurKeuangan: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    disbursementId: bigint,
    kaurKeuangan: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    disbursementId: bigint;
    kaurKeuangan: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisbursementSubmittedEvent {
  export type InputTuple = [
    disbursementId: BigNumberish,
    proposalId: BigNumberish,
    nominal: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    disbursementId: bigint,
    proposalId: bigint,
    nominal: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    disbursementId: bigint;
    proposalId: bigint;
    nominal: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InterventionRejectedEvent {
  export type InputTuple = [
    disbursementId: BigNumberish,
    kades: AddressLike,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    disbursementId: bigint,
    kades: string,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    disbursementId: bigint;
    kades: string;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LpjDesaSubmittedEvent {
  export type InputTuple = [
    tahun: BigNumberish,
    semester: BigNumberish,
    kades: AddressLike,
    lpjHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tahun: bigint,
    semester: bigint,
    kades: string,
    lpjHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tahun: bigint;
    semester: bigint;
    kades: string;
    lpjHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LpjKeuanganSubmittedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    kaurKeuangan: AddressLike,
    lpjHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    kaurKeuangan: string,
    lpjHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    kaurKeuangan: string;
    lpjHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LpjTeknisSubmittedEvent {
  export type InputTuple = [
    disbursementId: BigNumberish,
    kaurTeknis: AddressLike,
    totalAmount: BigNumberish,
    lpjHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    disbursementId: bigint,
    kaurTeknis: string,
    totalAmount: bigint,
    lpjHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    disbursementId: bigint;
    kaurTeknis: string;
    totalAmount: bigint;
    lpjHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRegisteredEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    kaurTeknis: AddressLike,
    dokumenHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    kaurTeknis: string,
    dokumenHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    kaurTeknis: string;
    dokumenHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReturnedForRevisionEvent {
  export type InputTuple = [
    disbursementId: BigNumberish,
    catatan: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    disbursementId: bigint,
    catatan: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    disbursementId: bigint;
    catatan: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedBySekdesEvent {
  export type InputTuple = [
    disbursementId: BigNumberish,
    sekdes: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    disbursementId: bigint,
    sekdes: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    disbursementId: bigint;
    sekdes: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DanaDesaLedger extends BaseContract {
  connect(runner?: ContractRunner | null): DanaDesaLedger;
  waitForDeployment(): Promise<this>;

  interface: DanaDesaLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  KADES_ROLE: TypedContractMethod<[], [string], "view">;

  KAUR_KEUANGAN_ROLE: TypedContractMethod<[], [string], "view">;

  KAUR_ROLE: TypedContractMethod<[], [string], "view">;

  SEKDES_ROLE: TypedContractMethod<[], [string], "view">;

  authorizeByKades: TypedContractMethod<
    [disbursementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  disbursements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        proposalId: bigint;
        nominal: bigint;
        beritaAcaraHash: string;
        geotag: string;
        status: bigint;
        kaurTeknis: string;
        sekdesVerifier: string;
        kadesApprover: string;
        catatanRevisi: string;
        submittedAt: bigint;
        verifiedAt: bigint;
        disbursedAt: bigint;
        lpjHash: string;
        lpjAmount: bigint;
      }
    ],
    "view"
  >;

  executeDisbursement: TypedContractMethod<
    [disbursementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSisaPagu: TypedContractMethod<
    [proposalId: BigNumberish],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lpjDesaHashes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, string, bigint, string] & {
        id: bigint;
        dusun: string;
        kategori: string;
        paguMaksimal: bigint;
        kaurTeknis: string;
        dokumenHash: string;
        createdAt: bigint;
        lpjKeuanganHash: string;
      }
    ],
    "view"
  >;

  registerProposal: TypedContractMethod<
    [
      dusun: string,
      kategori: string,
      paguMaksimal: BigNumberish,
      dokumenHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  rejectIntervention: TypedContractMethod<
    [disbursementId: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  returnForRevision: TypedContractMethod<
    [disbursementId: BigNumberish, catatan: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  submitDisbursement: TypedContractMethod<
    [
      proposalId: BigNumberish,
      nominal: BigNumberish,
      beritaAcaraHash: BytesLike,
      geotag: string
    ],
    [void],
    "nonpayable"
  >;

  submitLpjDesa: TypedContractMethod<
    [tahun: BigNumberish, semester: BigNumberish, lpjHash: BytesLike],
    [void],
    "nonpayable"
  >;

  submitLpjKeuangan: TypedContractMethod<
    [proposalId: BigNumberish, lpjHash: BytesLike],
    [void],
    "nonpayable"
  >;

  submitLpjTeknis: TypedContractMethod<
    [
      disbursementId: BigNumberish,
      totalAmount: BigNumberish,
      lpjHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalDisbursedPerProposal: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  verifyBySekdes: TypedContractMethod<
    [disbursementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyHash: TypedContractMethod<
    [disbursementId: BigNumberish, uploadedHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KADES_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KAUR_KEUANGAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KAUR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SEKDES_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeByKades"
  ): TypedContractMethod<[disbursementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disbursements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        proposalId: bigint;
        nominal: bigint;
        beritaAcaraHash: string;
        geotag: string;
        status: bigint;
        kaurTeknis: string;
        sekdesVerifier: string;
        kadesApprover: string;
        catatanRevisi: string;
        submittedAt: bigint;
        verifiedAt: bigint;
        disbursedAt: bigint;
        lpjHash: string;
        lpjAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeDisbursement"
  ): TypedContractMethod<[disbursementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSisaPagu"
  ): TypedContractMethod<[proposalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpjDesaHashes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, string, bigint, string] & {
        id: bigint;
        dusun: string;
        kategori: string;
        paguMaksimal: bigint;
        kaurTeknis: string;
        dokumenHash: string;
        createdAt: bigint;
        lpjKeuanganHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProposal"
  ): TypedContractMethod<
    [
      dusun: string,
      kategori: string,
      paguMaksimal: BigNumberish,
      dokumenHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectIntervention"
  ): TypedContractMethod<
    [disbursementId: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "returnForRevision"
  ): TypedContractMethod<
    [disbursementId: BigNumberish, catatan: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDisbursement"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      nominal: BigNumberish,
      beritaAcaraHash: BytesLike,
      geotag: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitLpjDesa"
  ): TypedContractMethod<
    [tahun: BigNumberish, semester: BigNumberish, lpjHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitLpjKeuangan"
  ): TypedContractMethod<
    [proposalId: BigNumberish, lpjHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitLpjTeknis"
  ): TypedContractMethod<
    [
      disbursementId: BigNumberish,
      totalAmount: BigNumberish,
      lpjHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalDisbursedPerProposal"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyBySekdes"
  ): TypedContractMethod<[disbursementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [disbursementId: BigNumberish, uploadedHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AuthorizedByKades"
  ): TypedContractEvent<
    AuthorizedByKadesEvent.InputTuple,
    AuthorizedByKadesEvent.OutputTuple,
    AuthorizedByKadesEvent.OutputObject
  >;
  getEvent(
    key: "Disbursed"
  ): TypedContractEvent<
    DisbursedEvent.InputTuple,
    DisbursedEvent.OutputTuple,
    DisbursedEvent.OutputObject
  >;
  getEvent(
    key: "DisbursementSubmitted"
  ): TypedContractEvent<
    DisbursementSubmittedEvent.InputTuple,
    DisbursementSubmittedEvent.OutputTuple,
    DisbursementSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "InterventionRejected"
  ): TypedContractEvent<
    InterventionRejectedEvent.InputTuple,
    InterventionRejectedEvent.OutputTuple,
    InterventionRejectedEvent.OutputObject
  >;
  getEvent(
    key: "LpjDesaSubmitted"
  ): TypedContractEvent<
    LpjDesaSubmittedEvent.InputTuple,
    LpjDesaSubmittedEvent.OutputTuple,
    LpjDesaSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "LpjKeuanganSubmitted"
  ): TypedContractEvent<
    LpjKeuanganSubmittedEvent.InputTuple,
    LpjKeuanganSubmittedEvent.OutputTuple,
    LpjKeuanganSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "LpjTeknisSubmitted"
  ): TypedContractEvent<
    LpjTeknisSubmittedEvent.InputTuple,
    LpjTeknisSubmittedEvent.OutputTuple,
    LpjTeknisSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRegistered"
  ): TypedContractEvent<
    ProposalRegisteredEvent.InputTuple,
    ProposalRegisteredEvent.OutputTuple,
    ProposalRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ReturnedForRevision"
  ): TypedContractEvent<
    ReturnedForRevisionEvent.InputTuple,
    ReturnedForRevisionEvent.OutputTuple,
    ReturnedForRevisionEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedBySekdes"
  ): TypedContractEvent<
    VerifiedBySekdesEvent.InputTuple,
    VerifiedBySekdesEvent.OutputTuple,
    VerifiedBySekdesEvent.OutputObject
  >;

  filters: {
    "AuthorizedByKades(uint256,address,uint256)": TypedContractEvent<
      AuthorizedByKadesEvent.InputTuple,
      AuthorizedByKadesEvent.OutputTuple,
      AuthorizedByKadesEvent.OutputObject
    >;
    AuthorizedByKades: TypedContractEvent<
      AuthorizedByKadesEvent.InputTuple,
      AuthorizedByKadesEvent.OutputTuple,
      AuthorizedByKadesEvent.OutputObject
    >;

    "Disbursed(uint256,address,uint256)": TypedContractEvent<
      DisbursedEvent.InputTuple,
      DisbursedEvent.OutputTuple,
      DisbursedEvent.OutputObject
    >;
    Disbursed: TypedContractEvent<
      DisbursedEvent.InputTuple,
      DisbursedEvent.OutputTuple,
      DisbursedEvent.OutputObject
    >;

    "DisbursementSubmitted(uint256,uint256,uint256,uint256)": TypedContractEvent<
      DisbursementSubmittedEvent.InputTuple,
      DisbursementSubmittedEvent.OutputTuple,
      DisbursementSubmittedEvent.OutputObject
    >;
    DisbursementSubmitted: TypedContractEvent<
      DisbursementSubmittedEvent.InputTuple,
      DisbursementSubmittedEvent.OutputTuple,
      DisbursementSubmittedEvent.OutputObject
    >;

    "InterventionRejected(uint256,address,bytes32,uint256)": TypedContractEvent<
      InterventionRejectedEvent.InputTuple,
      InterventionRejectedEvent.OutputTuple,
      InterventionRejectedEvent.OutputObject
    >;
    InterventionRejected: TypedContractEvent<
      InterventionRejectedEvent.InputTuple,
      InterventionRejectedEvent.OutputTuple,
      InterventionRejectedEvent.OutputObject
    >;

    "LpjDesaSubmitted(uint256,uint8,address,bytes32,uint256)": TypedContractEvent<
      LpjDesaSubmittedEvent.InputTuple,
      LpjDesaSubmittedEvent.OutputTuple,
      LpjDesaSubmittedEvent.OutputObject
    >;
    LpjDesaSubmitted: TypedContractEvent<
      LpjDesaSubmittedEvent.InputTuple,
      LpjDesaSubmittedEvent.OutputTuple,
      LpjDesaSubmittedEvent.OutputObject
    >;

    "LpjKeuanganSubmitted(uint256,address,bytes32,uint256)": TypedContractEvent<
      LpjKeuanganSubmittedEvent.InputTuple,
      LpjKeuanganSubmittedEvent.OutputTuple,
      LpjKeuanganSubmittedEvent.OutputObject
    >;
    LpjKeuanganSubmitted: TypedContractEvent<
      LpjKeuanganSubmittedEvent.InputTuple,
      LpjKeuanganSubmittedEvent.OutputTuple,
      LpjKeuanganSubmittedEvent.OutputObject
    >;

    "LpjTeknisSubmitted(uint256,address,uint256,bytes32,uint256)": TypedContractEvent<
      LpjTeknisSubmittedEvent.InputTuple,
      LpjTeknisSubmittedEvent.OutputTuple,
      LpjTeknisSubmittedEvent.OutputObject
    >;
    LpjTeknisSubmitted: TypedContractEvent<
      LpjTeknisSubmittedEvent.InputTuple,
      LpjTeknisSubmittedEvent.OutputTuple,
      LpjTeknisSubmittedEvent.OutputObject
    >;

    "ProposalRegistered(uint256,address,bytes32,uint256)": TypedContractEvent<
      ProposalRegisteredEvent.InputTuple,
      ProposalRegisteredEvent.OutputTuple,
      ProposalRegisteredEvent.OutputObject
    >;
    ProposalRegistered: TypedContractEvent<
      ProposalRegisteredEvent.InputTuple,
      ProposalRegisteredEvent.OutputTuple,
      ProposalRegisteredEvent.OutputObject
    >;

    "ReturnedForRevision(uint256,string,uint256)": TypedContractEvent<
      ReturnedForRevisionEvent.InputTuple,
      ReturnedForRevisionEvent.OutputTuple,
      ReturnedForRevisionEvent.OutputObject
    >;
    ReturnedForRevision: TypedContractEvent<
      ReturnedForRevisionEvent.InputTuple,
      ReturnedForRevisionEvent.OutputTuple,
      ReturnedForRevisionEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "VerifiedBySekdes(uint256,address,uint256)": TypedContractEvent<
      VerifiedBySekdesEvent.InputTuple,
      VerifiedBySekdesEvent.OutputTuple,
      VerifiedBySekdesEvent.OutputObject
    >;
    VerifiedBySekdes: TypedContractEvent<
      VerifiedBySekdesEvent.InputTuple,
      VerifiedBySekdesEvent.OutputTuple,
      VerifiedBySekdesEvent.OutputObject
    >;
  };
}
